# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b657a607234dd2bdf5986db4b4bbb00d284359b2f51590a083968eeba192a00aff4444498fbdbada9c407b79b0294984ae4f51a98c101ea63b2114b222d91ca

test:
  secret_key_base: 2b2d5939da977d5f7a66a7e700c0408fa0406aa4cc58ca0a07544a51be3f7930113c7bc89d0c42d185e192e6e4a073e1cdbde2a26754b345fa7590cf3ba75866

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
